Numpy is a fundamental library for sceintific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

In [2]:
#create array using numpy
#create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
#create a 2D array
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2 = np.array([[1, 2, 3, 4, 5]]) #for creating 2D array need 2 square brackets
arr2.shape

(1, 5)

In [11]:
arr2 = np.array([[1, 2, 3, 4, 5], [ 2, 3, 4, 5, 6]]) #for creating 2D array need 2 square brackets
print(arr2) 
arr2.shape
#(2, 5) is 2 rows and 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [13]:
np.arange(0, 10, 2) #creates an array from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0,10,2).reshape(5,1) #reshapes the array to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
# attributes of an Numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [17]:
#Numpy Vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])
#Element wise addition of two arrays which preent in same index position
#Element-wise addition
print("Addition:\n", arr1 + arr2)

#Element-wise subtraction
print("Subtraction:\n", arr1 - arr2)    

#Element-wise multiplication
print("Multiplication:\n", arr1 * arr2)

#Element-wise division
print("Division:\n", arr1 / arr2)

Addition:
 [ 3  6  9 12 15]
Subtraction:
 [-1 -2 -3 -4 -5]
Multiplication:
 [ 2  8 18 32 50]
Division:
 [0.5 0.5 0.5 0.5 0.5]


In [18]:
## Universal Functions
arr = np.array([1, 2, 3, 4, 5])

#Square root
print("Square root:\n", np.sqrt(arr))

#Exponential
print("Exponential:\n", np.exp(arr))

## Sine
print("Sine:\n", np.sin(arr))

## Natural log
print("Natural logarithm:\n", np.log(arr))

Square root:
 [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural logarithm:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [19]:
## Array Slicing and indexing

arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [30]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [25]:
arr[1:,1:] 

array([[ 6,  7,  8],
       [10, 11, 12]])

In [35]:
##Modifying Arrays

arr[1,2] = 7
print(arr)

[[10  2  3  4]
 [ 5 10  7  8]
 [ 9 10 11 12]]


In [36]:
## statistical concepts
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation

mean = np.mean(data)
sd = np.std(data)

#normalize the data
normalized_data = (data - mean) / sd
print("Normalized data: ",normalized_data)


Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean: ",mean)

#Median
median = np.median(data)
print("Median: ",median)

#Standard deviation
sd = np.std(data)
print("Standard deviation: ",sd)

#Variance
var = np.var(data)
print("Variance: ",var)

Mean:  5.5
Median:  5.5
Standard deviation:  2.8722813232690143
Variance:  8.25


In [42]:
##Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#greater than 5
print(data > 5)
print(data[data > 5])
data[(data >= 5) & (data <= 8)]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


array([5, 6, 7, 8])