# Module: NumPy Exercise
###  1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [10]:
array = np.random.randint(1,20, size=(5,5))
print("original array\n",array)

#replace all elements in the 3rd array with 1
array[0:5,2]=1
print("modified array\n",array)

original array
 [[11  5 11  2  4]
 [15  9  7 14 10]
 [17  9 10 15 18]
 [14  7  9  6 14]
 [ 4  1 14  4  6]]
modified array
 [[11  5  1  2  4]
 [15  9  1 14 10]
 [17  9  1 15 18]
 [14  7  1  6 14]
 [ 4  1  1  4  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [13]:
array = np.arange(1,17).reshape(4,4)
print("original array\n",array)

#replace the diagonal elements with 0
np.fill_diagonal(array,0)
print("modified array\n",array)

original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


###  2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [15]:
array =np.random.randint(1,36, size=(6,6))
print("original array\n",array)

#Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns
array = array[2:5,1:4]
print("sub-array\n",array)

original array
 [[ 9 32 23  8 13  8]
 [29 19 23 15 14 28]
 [24  3 12 14  9 10]
 [ 4 27 21  5 11 19]
 [10 15 14 30 11 12]
 [ 2 15  8  4 19 27]]
sub-array
 [[ 3 12 14]
 [27 21  5]
 [15 14 30]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [20]:
array = np.random.randint(1,36, size=(5,5))

#Print the array
print("original array\n",array)

#Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1,-1]))
print("sub-array\n",border_elements)

original array
 [[11 15 22  5  7]
 [34 28 15  5 21]
 [14 17 19 35  2]
 [ 3  4 15 27 21]
 [ 3 25 24 33  9]]
sub-array
 [11 15 22  5  7  3 25 24 33  9 34 14  3 21  2 21]


###  3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [22]:
array1 = np.random.randint(1,11, size=(3,4))
array2 = np.random.randint(1,11, size=(3,4))
#Print the array
print("original array\n",array1)
print("original array\n",array2)

#addition of two arrays
sum_of_arrays = array1 + array2
print("sum of arrays\n",sum_of_arrays)

#subtraction of two arrays
difference_of_arrays = array1 - array2
print("difference of arrays\n",difference_of_arrays)

#multiplication of two arrays
product_of_arrays = array1 * array2
print("product of arrays\n",product_of_arrays)

#division of two arrays
division_of_arrays = array1 / array2
print("division of arrays\n",division_of_arrays)

original array
 [[4 4 7 1]
 [9 1 5 8]
 [2 4 1 6]]
original array
 [[ 1  8  7  7]
 [ 9 10  3 10]
 [ 7  9  7 10]]
sum of arrays
 [[ 5 12 14  8]
 [18 11  8 18]
 [ 9 13  8 16]]
difference of arrays
 [[ 3 -4  0 -6]
 [ 0 -9  2 -2]
 [-5 -5 -6 -4]]
product of arrays
 [[ 4 32 49  7]
 [81 10 15 80]
 [14 36  7 60]]
division of arrays
 [[4.         0.5        1.         0.14285714]
 [1.         0.1        1.66666667 0.8       ]
 [0.28571429 0.44444444 0.14285714 0.6       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [24]:
array = np.random.randint(1,16, size=(4,4))
#Print the array
print("original array\n",array)

#Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)
print("sum of rows\n",row_sum)
print("sum of columns\n",column_sum)


original array
 [[ 2  9  9  6]
 [ 9  8  6 12]
 [11  4  8  6]
 [ 2  3  1  7]]
sum of rows
 [26 35 29 13]
sum of columns
 [24 24 24 31]


###  4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [25]:
array = np.random.randint(1,16, size=(5,5))

#Print the array    
print("original array\n",array)

#Compute the statistical operations
mean = np.mean(array)
median =np.median(array)
std = np.std(array)
variance = np.var(array)
print("mean\n",mean)
print("median\n",median)
print("standard deviation\n",std)
print("variance\n",variance)

original array
 [[ 1  4  9 13 11]
 [15  1  6 13  4]
 [12  6  7  9 12]
 [ 1  3 13 11  3]
 [ 2  4 14 10  8]]
mean
 7.68
median
 8.0
standard deviation
 4.487493732586153
variance
 20.137600000000003


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [26]:
array =np.random.randint(1,9, size=(3,3))

#Print the array
print("original array\n",array)

#Normaliza the array
normalized_array = (array - np.mean(array)) / (np.std(array))
print("normalized array\n",normalized_array)

original array
 [[1 6 8]
 [4 3 3]
 [8 2 5]]
normalized array
 [[-1.45811735  0.65850461  1.50515339]
 [-0.18814417 -0.61146856 -0.61146856]
 [ 1.50515339 -1.03479296  0.23518022]]


### 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [27]:
array = np.random.randint(1,16, size=(3,3))
row_array =np.random.randint(1,16, size=(3,))

#Print the array
print("original array\n",array)
print("1 Dimensional array\n",row_array)

#Add the 1D array to each row of the 2D array using broadcasting

result = array + row_array
print("result\n",result)

original array
 [[15  6  9]
 [ 7  7 14]
 [ 5 11 13]]
1 Dimensional array
 [13  6  8]
result
 [[28 12 17]
 [20 13 22]
 [18 17 21]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [29]:
array = np.random.randint(1,16, size=(4,4))
column_array =np.random.randint(1,16, size=(4,))

#Print the array
print("original array\n",array)
print("1 Dimensional array\n",column_array)

#Subtract the 1D array  from each column of the 2D array using broadcasting.

result = array - column_array[:, np.newaxis]
print("result\n",result)

original array
 [[ 2  7  9  4]
 [ 2 12  9 12]
 [13  5 10  7]
 [ 2  1 11 13]]
1 Dimensional array
 [ 2  8  2 11]
result
 [[  0   5   7   2]
 [ -6   4   1   4]
 [ 11   3   8   5]
 [ -9 -10   0   2]]


### 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [31]:
matrix = np.random.randint(1,16, size=(3,3))

#Print the matrix
print("original matrix\n",matrix)

#Compute its determinant
determinant = np.linalg.det(matrix)
print("determinant\n",determinant)

#Compute its inverse
inverse = np.linalg.inv(matrix)
print("inverse\n",inverse)

#compute its eigenvalues
eigenvalues = np.linalg.eig(matrix)
print("eigenvalues\n",eigenvalues)


original matrix
 [[14 15  6]
 [ 5  7 11]
 [15  7 14]]
determinant
 1299.0000000000002
inverse
 [[ 0.01616628 -0.12933025  0.09468822]
 [ 0.07313318  0.08160123 -0.09545804]
 [-0.05388761  0.09776751  0.01770593]]
eigenvalues
 EigResult(eigenvalues=array([31.55068836+0.j        ,  1.72465582+6.18040498j,
        1.72465582-6.18040498j]), eigenvectors=array([[ 0.59669151+0.j        , -0.6257617 +0.j        ,
        -0.6257617 -0.j        ],
       [ 0.42617611+0.j        ,  0.37513938-0.42335225j,
         0.37513938+0.42335225j],
       [ 0.67995085+0.j        ,  0.34239159+0.41380383j,
         0.34239159-0.41380383j]]))


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [35]:
array1 = np.random.randint(1,16, size=(2,3))
array2 = np.random.randint(1,16, size=(3,2))

#Print the array
print("original array1\n",array1)
print("original array2\n",array2)

#Perform matrix multiplication
dot_product = np.dot(array1,array2)
print("matrix multiplication result\n",dot_product)

original array1
 [[12 11  1]
 [12 10  8]]
original array2
 [[ 9  1]
 [ 1 15]
 [ 2 14]]
matrix multiplication result
 [[121 191]
 [134 274]]


### 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [36]:
array = np.random.randint(1,9, size=(3,3))

#Print the array
print("original array\n",array)

#Reshape the array to shape (1,9)
reshaped_array1 = array.reshape(1,9)
print("reshaped array1 (1,9)\n",reshaped_array1)

#Reshape the array to shape (9,1)
reshaped_array2 = array.reshape(9,1)
print("reshaped array2 (9,1)\n",reshaped_array2)

original array
 [[7 6 2]
 [2 5 4]
 [6 5 5]]
reshaped array1 (1,9)
 [[7 6 2 2 5 4 6 5 5]]
reshaped array2 (9,1)
 [[7]
 [6]
 [2]
 [2]
 [5]
 [4]
 [6]
 [5]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [38]:
array = np.random.randint(1,16, size=(5,5))

#Print the array
print("original array\n",array)

#Flatten the array
flattened_array = array.flatten()
print("flattened array\n",flattened_array)

#reshape the flatten array to shape (5,5)
reshaped_array = flattened_array.reshape(5,5)
print("reshaped array\n",reshaped_array)

original array
 [[12 12 11 10 14]
 [ 7  3  7  8  4]
 [ 2 12  4  1  3]
 [ 6  8 10  4 13]
 [ 5 11  4  2  5]]
flattened array
 [12 12 11 10 14  7  3  7  8  4  2 12  4  1  3  6  8 10  4 13  5 11  4  2
  5]
reshaped array
 [[12 12 11 10 14]
 [ 7  3  7  8  4]
 [ 2 12  4  1  3]
 [ 6  8 10  4 13]
 [ 5 11  4  2  5]]


###  8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [39]:
array = np.random.randint(1,16, size=(5,5))

#Print the array
print("original array\n",array)

#Use fancy indexing to extract the elements at the corners of the array.

corner_elements = array[[0,0,4,4],[0,4,0,4]]
print("corner elements\n",corner_elements)

original array
 [[13  3  8  1  6]
 [12  7 14 12  1]
 [ 3  6 14  4 10]
 [13 13  8 10 12]
 [ 9 15  4  2  8]]
corner elements
 [13  6  9  8]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [40]:
array = np.random.randint(1,16, size=(4,4))

#Print the array
print("original array\n",array)

#Use boolean indexing to set all elements greater than 10 to 10.

array[array > 10] = 10
print("modified array\n",array)

original array
 [[ 2 13  2 14]
 [ 1  6 14  5]
 [15  3  6  1]
 [13 10  9  4]]
modified array
 [[ 2 10  2 10]
 [ 1  6 10  5]
 [10  3  6  1]
 [10 10  9  4]]


### 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [43]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 45, 55.0), ('Bob', 30, 60.5), ('Charlie', 35, 65.0)], dtype=data_type)

# Print the structured array
print("structured array\n",data)

# Sort the structured array by age
sorted_data = np.sort(data, order='age')
print("sorted array\n",sorted_data)

structured array
 [('Alice', 45, 55. ) ('Bob', 30, 60.5) ('Charlie', 35, 65. )]
sorted array
 [('Bob', 30, 60.5) ('Charlie', 35, 65. ) ('Alice', 45, 55. )]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [45]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 10), (3, 4)], dtype=data_type)
print("structured array\n",data)

#compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances\n",distances)

structured array
 [(1, 10) (3,  4)]
Euclidean distances
 [[0.         6.32455532]
 [6.32455532 0.        ]]


### 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [47]:
import numpy.ma as ma
array =np.random.randint(1,16, size=(4,4))

#Print the array
print("original array\n",array)

masked_array = ma.masked_greater(array,10)
print("masked array\n",masked_array)

#compute the sum of unmasked elements
sum_unmasked = masked_array.sum()
print("sum of unmasked elements\n",sum_unmasked)

original array
 [[10  1 15  4]
 [15  5  4  6]
 [11 11  7  2]
 [ 8  9  8 10]]
masked array
 [[10 1 -- 4]
 [-- 5 4 6]
 [-- -- 7 2]
 [8 9 8 10]]
sum of unmasked elements
 74


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [48]:
array =np.random.randint(1,16, size=(3,3))

#Print the array
print("original array\n",array)

masked_array = ma.masked_array(array,mask=np.eye(3, dtype=bool))
print("masked array\n",masked_array)

#find the mean of the non-masked elements
mean_unmasked = masked_array.mean()
print("mean of unmasked elements\n",mean_unmasked)

#replace the masked elements with the mean of the non-masked elements
masked_array = masked_array.filled(mean_unmasked)
print("masked array\n",masked_array)

original array
 [[ 9  5 12]
 [ 9 14  6]
 [ 3  5  4]]
masked array
 [[-- 5 12]
 [9 -- 6]
 [3 5 --]]
mean of unmasked elements
 6.666666666666667
masked array
 [[ 6  5 12]
 [ 9  6  6]
 [ 3  5  6]]
